# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
	  - develop
  paths:
    include:
      - NowPlaying.Api.Cinema/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build NowPlaying.Api.Cinema/NowPlaying.Api.Cinema.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
